### PR TITLE
Migration guide for ESR 91

### PR DESCRIPTION
**Pull request by ptomato**
I've taken the migration notes and turned them into a full migration guide, adding recommendations and examples where applicable. I think after this we can make the `next` branch into `esr91` and start a new `next` branch!

### CODE REVIEW

**Comment by evilpie** [comment]
@ptomato Are these build failures expected?

**Comment by ptomato** [comment]
@evilpie I'm guessing that there's some header that's not getting installed in the current mozilla-beta SM tarball? I'm hoping that these failures would go away if we built a mozilla-esr91 tarball (though if mozilla-beta is broken for embedders that should probably be looked into.)

**Comment by ptomato** [comment]
That seems to have fixed things.

**Review by mgaudet — APPROVED** [review]
Thanks!

**Pull request merged**
