### PR TITLE
Explicitly create configure script from configure.in

### PR DESCRIPTION
**Pull request by arai-a**

### CODE REVIEW

**Comment by ptomato** [comment]
Is this new, and if so, is it intended? The `configure` script is still present in the SpiderMonkey tarballs I get from treeherder, and it's executable as well. If it's not present or executable in the main Firefox source tarballs, then maybe it's a regression?

**Comment by arai-a** [comment]
`configure` script hasn't been a part of source.  it has been a file generated by autoconf.

[make-source-package.py](https://searchfox.org/mozilla-central/rev/81c95e56daabc6b6cd84b65349fc6163c490f957/js/src/make-source-package.py#375-407) generates `configure` script and stores int into SpiderMonkey tarball.

Then, https://bugzilla.mozilla.org/show_bug.cgi?id=1295751 made the `configure.in` a shell script, and "creating `configure` from `configure.in`" became just a copy at that point.

**Comment by arai-a** [comment]
So, to be clear, this step is necessary when using the firefox ESR source tarball (that's snapshot of mozilla-esr*),
and not necessary when using SpiderMonkey tarball.

**Review by ptomato — APPROVED** [review]
Oh, okay, thanks for clarifying. I thought that the main Firefox tarballs also contained that script, but maybe that changed much longer ago.

**Pull request merged**
