### PR TITLE
Example of a custom trace hook

### PR DESCRIPTION
**Pull request by hotsphink**
I was lazy, and updated to -std=c++20 to use a designated initializer. It makes creating JSClassOps much quicker and nicer.

### CODE REVIEW

**Comment by hotsphink** [comment]
Er, I messed up and based this on my local custom.err branch. Which has now landed. I rebased it onto the landed esr115 tip and re-pushed. I don't know if I need to do anything else.

**Comment by ptomato** [comment]
No problem. If I was reviewing it I'd have one question about whether to use `JS::GetMaybePtrFromReservedSlot()` in `CustomObject::ownedBox()` and `CustomObject::unownedBox()`. On the one hand it seems like we don't need the `isUndefined()` check, but on the other hand we do check that the pointer isn't null before tracing.

**Comment by hotsphink** [comment]
I tried using `JS::GetMaybePtrFromReservedSlot` first, and got a compile error. But I just tried it again, and it worked fine. I must have done something wrong. (I think I misinterpreted the error to be saying that it needed my object type to inherit from `JSObject`, which isn't possible, but that's no different from any other API that takes `JSObject*`.)

I guess I'll make a PR for the change, and you can add any other comments there.

**Comment by hotsphink** [comment]
https://github.com/mozilla-spidermonkey/spidermonkey-embedding-examples/pull/84

**Pull request closed without merging**
