### PR TITLE
Update LICENSE to dual MIT / Apache 2.0

### PR DESCRIPTION
**Pull request by moztcampbell**
Convert the license of this repository to dual MIT / Apache 2.0 license and transfer copyright name to Mozilla Foundation. The Pull Request will seek approvals of all past contributors.

### CODE REVIEW

**Comment by moztcampbell** [comment]
This follows the Mozilla licensing run-book guidelines. The intent is that this repo can be consumed under either license, with code added supporting both.

Using the example from Rust project, contributors should comment here with `I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.`

@jandem @jorendorff @hotsphink @tynopex @ptomato

**Comment by tynopex** [comment]
(Doing this from original account to avoid confusion)
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jandem** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ptomato** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Review by ptomato — APPROVED** [review]

**Comment by hotsphink** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Pull request merged**
